name: Build and publish pegasus Docker images

on:
  push:
    paths:
      - 'pegasus-build-push/**'
      - '.github/workflows/build-env.yml'
  pull_request:
    types: [ synchronize, opened, reopened ]

  # for manually triggering workflow
  workflow_dispatch:

jobs:
  build_docker_images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dockertag:
          - ubuntu1604
          - ubuntu1804
          - ubuntu2004
          #- centos6 is EOL
          - centos7
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to Github Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        env:
          RELEASE_VERSION: v2.3.0
        with:
          context: .
          file: ./pegasus-build-push/${{ matrix.dockertag }}/Dockerfile
          push: true
          tags: |
            apachepegasus/build-env:${{ RELEASE_VERSION }}_${{ matrix.dockertag }}
            ghcr.io/pegasus-kv/build-env:${{ RELEASE_VERSION }}_${{ matrix.dockertag }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
