name: Build and publish pegasus Docker images

on:
  push:
    paths:
      - 'pegasus-build-push/**'
      - '.github/workflows/build-push-docker.yml'

  # for manually triggering workflow
  workflow_dispatch:

jobs:
  build_docker_images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      env:
        RELEASE_VERSION: v2.3.0
      matrix:
        dockertag:
          - ${{ RELEASE_VERSION }}_ubuntu1604
          - ${{ RELEASE_VERSION }}_ubuntu1804
          - ${{ RELEASE_VERSION }}_ubuntu2004
          #- centos6 is EOL
          - ${{ RELEASE_VERSION }}_centos7
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./pegasus-build-push/${{ matrix.dockertag }}/Dockerfile
          push: true
          tags: |
            apachepegasus/release:${{ matrix.dockertag }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
