name: Build and upload third-party binary package to GHCR

on:
  push:
    paths:
      - 'thirdparties-bin/**'
      - '.github/workflows/thirdparties-bin.yml'

  # for manually triggering workflow
  workflow_dispatch:

jobs:
  build_docker_images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        osversion:
          - ubuntu1604
          - ubuntu1804
          - ubuntu2004
          #- centos6 is EOL
          - centos7
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./thirdparties-bin/Dockerfile
          push: true
          tags: ghcr.io/pegasus-kv/thirdparties-bin:${{ matrix.osversion }}
          build-args: |
            OS_VERSION=${{ matrix.osversion }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
