name: Build and upload third-party source package to GHCR

on:
  push:
    paths:
      - 'thirdparties-src/**'
  workflow_dispatch

jobs:
  build_docker_images:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Github Container Registry
        uses: docker/login-action@v1 
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./thirdparties-src/Dockerfile
          push: true
          tags: ghcr.io/pegasus-kv/thirdparties-src
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
